dating/config/routes.rb
Dating::Application.routes.draw do

  get "videos/new"

  get "videos/index"

  get "videos/edit"

  mount Ckeditor::Engine => '/ckeditor'

  scope :module => :web do
    scope "(:locale)", :locale => /ru|en/ do
      root :to => "welcome#index"

      resource :sessions, :only => [:new, :create, :destroy]
      resources :pages, :only => [:show]
      resources :action_requests, :only => [:create]

      namespace :admin do
        root :to => 'welcome#index'
        resources :users
        resources :pages
        resources :action_requests
        resources :places
        resources :dating_events
        resources :videos
      end
    end

  end

end

dating/app/models/user.rb
class User < ActiveRecord::Base
  include UsefullScopes

  attr_accessible :avatar,
                  :email,
                  :firstname,
                  :lastname,
                  :nickname,
                  :password,
                  :password_digest,
                  :remember_me,
                  :weburl

  has_secure_password
end

dating/app/controllers/web/admin/users_controller.rb
class Web::Admin::UsersController < Web::Admin::ApplicationController
  def index
    params[:search] ||= {:meta_sort => "id.desc"}
    @search = User.metasearch(params[:search])
    @users = @search.page params[:page]
    headline headline_translate(:title)
  end

  def new
    @user = User.new
    headline headline_translate(:title)
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:success] = flash_translate(:success)
      redirect_to edit_admin_user_path(@user)
    else
      flash[:error] = flash_translate(:error)
      render :action => :new
    end
  end

  def edit
    @user = User.find(params[:id])
    headline headline_translate(:title)
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      flash[:success] = flash_translate(:success)
      redirect_to admin_users_path
    else
      flash[:error] = flash_translate(:error)
      redirect_to edit_admin_user_path(@user)
    end
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      flash[:success] = flash_translate(:success)
    else
      flash[:error] = flash_translate(:error)
    end
    redirect_to admin_users_path
  end

  def show
    redirect_to edit_admin_user_path(params[:id])
  end
end

dating/app/helpers/web/admin/users_helper.rb
module Web::Admin::UsersHelper
end

dating/app/views/web/admin/users/_form.html.haml
- if f.error_notification
  .alert.error.fade.in= f.error_notification
%ul.nav.nav-tabs
  %li.active
    %a{:"data-toggle" => "tab", :href => "#infoTab"}= t(".tab.info_tab")
  %li
    %a{:"data-toggle" => "tab", :href => "#settingsTab"}= t(".tab.settings_tab")
.tab-content
  #infoTab.tab-pane.active
    = f.input :email, :input_html => { :class => "span6" }
    = f.input :firstname, :input_html => { :class => "span6" }
    = f.input :lastname, :input_html => { :class => "span6" }
    = f.input :nickname, :input_html => { :class => "span6" }
    = f.input :password, :input_html => { :class => "span6" }
    = f.input :weburl, :input_html => { :class => "span6" }
  #settingsTab.tab-pane
= f.button :submit

dating/app/views/web/admin/users/edit.html.haml
= simple_form_for @user, :url => admin_user_path(@user), :html => {:class => "form-horizontal"} do |f|
  = render "form", :f => f

dating/app/views/web/admin/users/index.html.haml
- if @users.any?
  %table.table.table-striped.table-bordered.table-condensed
    %thead
      %tr
        %td= sort_link @search, :id, User.human_attribute_name(:id)
        %td= sort_link @search, :email, User.human_attribute_name(:email)
        %td= sort_link @search, :nickname, User.human_attribute_name(:nickname)
        %td= sort_link @search, :created_at, User.human_attribute_name(:created_at)
        %td= sort_link @search, :updated_at, User.human_attribute_name(:updated_at)
        %td= t(".control")
    %tbody
      - @users.each do |user|
        %tr
          %td= user.id
          %td= link_to user.email, edit_admin_user_path(user)
          %td= user.nickname
          %td= l(user.created_at, :format => :full)
          %td= l(user.updated_at, :format => :full)
          %td
            = link_to edit_admin_user_path(user) do
              %i.icon-edit
            = link_to admin_user_path(user), :method => :delete, :data => { :confirm => t(".are_you_sure") } do
              %i.icon-trash

dating/app/views/web/admin/users/new.html.haml
= simple_form_for @user, :url => admin_users_path, :html => {:class => "form-horizontal"} do |f|
  = render "form", :f => f