dating/config/routes.rb
Dating::Application.routes.draw do

  get "videos/new"

  get "videos/index"

  get "videos/edit"

  mount Ckeditor::Engine => '/ckeditor'

  scope :module => :web do
    scope "(:locale)", :locale => /ru|en/ do
      root :to => "welcome#index"

      resource :sessions, :only => [:new, :create, :destroy]
      resources :pages, :only => [:show]
      resources :action_requests, :only => [:create]

      namespace :admin do
        root :to => 'welcome#index'
        resources :users
        resources :pages
        resources :action_requests
        resources :places
        resources :dating_events
        resources :videos
      end
    end

  end

end

dating/app/models/action_request.rb
class ActionRequest < ActiveRecord::Base
  include UsefullScopes

  attr_accessible :birthdate,
                  :cost,
                  :coupone_code,
                  :email,
                  :name,
                  :phone,
                  :sex

  belongs_to :dating_event

  class << self
    def avaliable_sexs
      [:male, :female]
    end
  end

  def human_sex_name
    scope = [:activerecord, :attributes, :request, :sexs]
    I18n.t(sex, :scope => scope)
  end
end

dating/app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
              
  delegate :url, :current_path, :size, :content_type, :filename, :to => :data
  
  validates_presence_of :data
end

dating/app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, :mount_on => :data_file_name
	
	def url_thumb
	  @url_thumb ||= Ckeditor::Utils.filethumb(filename)
	end
end

dating/app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, :mount_on => :data_file_name
	
	def url_content
	  url(:content)
	end
end

dating/app/models/dating_event.rb
class DatingEvent < ActiveRecord::Base
  include UsefullScopes

  attr_accessible :description,
                  :event_date,
                  :limit,
                  :name,
                  :place_id,
                  :state,
                  :time_end,
                  :time_start

  has_many :action_requests
  belongs_to :place

  state_machine :state, :initial => :unpublished do
    state :unpublished
    state :published

    event :publish do
      transition [:unpublished] => :published
    end

    event :unpublish do
      transition [:published] => :unpublished
    end
  end

  scope :published, with_state(:published)
  scope :unpublished, with_state(:unpublished)

end

dating/app/models/page.rb
class Page < ActiveRecord::Base
  include UsefullScopes

  attr_accessible :body, :slug, :state, :state_event, :title

  validates :title, :presence => true
  validates :body, :presence => true
  validates :slug, :presence => true

  state_machine :state, :initial => :unpublished do
    state :unpublished
    state :published

    event :publish do
      transition [:unpublished] => :published
    end

    event :unpublish do
      transition [:published] => :unpublished
    end
  end

  scope :published, with_state(:published)
  scope :unpublished, with_state(:unpublished)

end

dating/app/models/place.rb
class Place < ActiveRecord::Base
  include UsefullScopes

  attr_accessible :description,
                  :latitude,
                  :limit,
                  :longitude,
                  :map,
                  :name,
                  :state

  has_many :dating_events

  state_machine :state, :initial => :unpublished do
    state :unpublished
    state :published

    event :publish do
      transition [:unpublished] => :published
    end

    event :unpublish do
      transition [:published] => :unpublished
    end
  end

  scope :published, with_state(:published)
  scope :unpublished, with_state(:unpublished)

end

dating/app/models/place/asset.rb
class Place::Asset < ActiveRecord::Base
  include UsefullScopes

  attr_accessible :description,
                  :file,
                  :name
end

dating/app/models/request.rb
class Request < ActiveRecord::Base
  attr_accessible :birthdate,
                  :cost,
                  :coupone_code,
                  :email,
                  :name,
                  :phone,
                  :sex

  class << self
    def avaliable_sexs
      [:male, :female]
    end
  end

  def human_sex_name
    scope = [:activerecord, :attributes, :request, :sexs]
    I18n.t(sex, :scope => scope)
  end
end

dating/app/models/user.rb
class User < ActiveRecord::Base
  include UsefullScopes

  attr_accessible :avatar,
                  :email,
                  :firstname,
                  :lastname,
                  :nickname,
                  :password,
                  :password_digest,
                  :remember_me,
                  :weburl

  has_secure_password
end

dating/app/models/video.rb
class Video < ActiveRecord::Base
  include UsefullScopes

  attr_accessible :code,
                  :description,
                  :name,
                  :sort,
                  :state

  state_machine :state, :initial => :unpublished do
    state :unpublished
    state :published

    event :publish do
      transition [:unpublished] => :published
    end

    event :unpublish do
      transition [:published] => :unpublished
    end
  end

  scope :published, with_state(:published)
  scope :unpublished, with_state(:unpublished)


end

dating/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include AuthHelper
  include FlashHelper
  include HeadlineHelper
  include RequestTranslateHelper
end

dating/app/controllers/web/pages_controller.rb
class Web::PagesController < Web::ApplicationController

  before_filter :find_by_slug_or_id

  def show
    if params[:id].to_i == @page.id
      redirect_to page_path(@page.slug)
    end
  end

  def video
    @videos = @search.page params[:page]
  end

  private

  def find_by_slug_or_id
    @page = Page.published.find_by_slug(params[:id])
    if @page.nil?
      @page = Page.find(params[:id])
    end
  end
end

dating/app/controllers/web/sessions_controller.rb
class Web::SessionsController < Web::ApplicationController
  def index
  end

  def new
    @user = User.new
  end

  def create
    @user = User.find_by_email(params[:user][:email])
    if @user && @user.authenticate(params[:user][:password])
      sign_in(@user)
      redirect_to admin_root_path
    else
      @user = User.new(params[:user])
      flash[:alert] = t("authenticate_error")
      render :action => :new
    end

  end

  def destroy
    sign_out
    redirect_to :root
  end

  def update
  end
end

dating/app/controllers/web/welcome_controller.rb
class Web::WelcomeController < Web::ApplicationController
  def index

    @content = Page.published.last

  end
end

dating/app/helpers/application_helper.rb
module ApplicationHelper
end

dating/app/helpers/web/action_requests_helper.rb
module Web::ActionRequestsHelper
end

dating/app/helpers/web/pages_helper.rb
module Web::PagesHelper
end

dating/app/helpers/web/sessions_helper.rb
module Web::SessionsHelper
end

dating/app/helpers/web/welcome_helper.rb
module Web::WelcomeHelper
end

dating/app/views/layouts/web/admin/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Dating"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application_admin"
    %link(href="images/apple-touch-icon-144x144.png" rel="apple-touch-icon-precomposed" sizes="144x144")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon-precomposed" sizes="114x114")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon-precomposed")
    %link(href="images/favicon.ico" rel="shortcut icon")


  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand(href="/admin/") Dating
          .container.nav-collapse
            %ul.nav
              %li= link_to t(".pages"), admin_pages_path
              %li= link_to t(".users"), admin_users_path
              %li= link_to t(".requests"), admin_action_requests_path
              %li= link_to t(".dating_events"), admin_dating_events_path
              %li= link_to t(".places"), admin_places_path
              %li= link_to t(".videos"), admin_videos_path

    .container

      .content
        .row
          .span9
            %h1= headline
            = flash_block
            = yield
          .span3
            .well.sidebar-nav
              %h3 Sidebar
              %ul.nav.nav-list
                %li.nav-header Sidebar
                %li= link_to "Link 1", "/path1"
                %li= link_to "Link 2", "/path2"
                %li= link_to "Link 3", "/path3"

      %footer
        %p &copy; Company 2012
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster

dating/app/views/layouts/web/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Dating"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    = stylesheet_link_tag "application", :media => "all"
    %link(href="images/apple-touch-icon-144x144.png" rel="apple-touch-icon-precomposed" sizes="144x144")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon-precomposed" sizes="114x114")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon-precomposed")
    %link(href="images/favicon.ico" rel="shortcut icon")


  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand(href="#") Dating
          .container.nav-collapse
            %ul.nav
              %li= link_to "Link 1", "/path1"
              %li= link_to "Link 2", "/path2"
              %li= link_to "Link 3", "/path3"

    .container

      .content
        .row
          .span9
            = yield
          .span3
            .well.sidebar-nav
              %h3 Sidebar
              %ul.nav.nav-list
                %li.nav-header Sidebar
                %li= link_to "Link 1", "/path1"
                %li= link_to "Link 2", "/path2"
                %li= link_to "Link 3", "/path3"
    
      %footer
        %p &copy; Company 2012
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"

dating/app/views/web/admin/pages/_form.html.haml
- if f.error_notification
  .alert.error.fade.in= f.error_notification
%ul.nav.nav-tabs
  %li.active
    %a{:"data-toggle" => "tab", :href => "#infoTab"}= t(".tab.info_tab")
  %li
    %a{:"data-toggle" => "tab", :href => "#settingsTab"}= t(".tab.settings_tab")
.tab-content
  #infoTab.tab-pane.active
    = f.input :title, :input_html => { :class => "span6" }
    = f.input :body, :as => :ckeditor, :input_html => { :rows => 5 }, :toolbar => "Easy"
  #settingsTab.tab-pane
    = f.input :slug, :input_html => {:class => "span6"}
    = f.input :state_event, :as => :state, :include_blank => @page.human_state_name
= f.button :submit

dating/app/views/web/admin/pages/edit.html.haml
= simple_form_for @page, :url => admin_page_path(@page), :html => {:class => "form-horizontal"} do |f|
  = render "form", :f => f

dating/app/views/web/admin/pages/index.html.haml
- if @pages.any?
  %table.table.table-striped.table-bordered.table-condensed
    %thead
      %tr
        %td= sort_link @search, :id, Page.human_attribute_name(:id)
        %td= sort_link @search, :title, Page.human_attribute_name(:title)
        %td= sort_link @search, :slug, Page.human_attribute_name(:slug)
        %td= sort_link @search, :state, Page.human_attribute_name(:state)
        %td= sort_link @search, :created_at, Page.human_attribute_name(:created_at)
        %td= sort_link @search, :updated_at, Page.human_attribute_name(:updated_at)
        %td= t(".control")
    %tbody
      - @pages.each do |page|
        %tr
          %td= page.id
          %td= link_to page.title, edit_admin_page_path(page)
          %td= page.slug
          %td= page.human_state_name
          %td= l(page.created_at, :format => :full)
          %td= l(page.updated_at, :format => :full)
          %td
            = link_to edit_admin_page_path(page) do
              %i.icon-edit
            = link_to admin_page_path(page), :method => :delete, :data => { :confirm => t(".are_you_sure") } do
              %i.icon-trash

dating/app/views/web/admin/pages/new.html.haml
= simple_form_for @page, :url => admin_pages_path, :html => {:class => "form-horizontal"} do |f|
  = render "form", :f => f

dating/app/views/web/pages/show.html.haml
%h1= @page.title
= @page.body