dating/config/routes.rb
Dating::Application.routes.draw do

  get "videos/new"

  get "videos/index"

  get "videos/edit"

  mount Ckeditor::Engine => '/ckeditor'

  scope :module => :web do
    scope "(:locale)", :locale => /ru|en/ do
      root :to => "welcome#index"

      resource :sessions, :only => [:new, :create, :destroy]
      resources :pages, :only => [:show]
      resources :action_requests, :only => [:create]

      namespace :admin do
        root :to => 'welcome#index'
        resources :users
        resources :pages
        resources :action_requests
        resources :places
        resources :dating_events
        resources :videos
      end
    end

  end

end

dating/app/models/dating_event.rb
class DatingEvent < ActiveRecord::Base
  include UsefullScopes

  attr_accessible :description,
                  :event_date,
                  :limit,
                  :name,
                  :place_id,
                  :state,
                  :time_end,
                  :time_start

  has_many :action_requests
  belongs_to :place

  state_machine :state, :initial => :unpublished do
    state :unpublished
    state :published

    event :publish do
      transition [:unpublished] => :published
    end

    event :unpublish do
      transition [:published] => :unpublished
    end
  end

  scope :published, with_state(:published)
  scope :unpublished, with_state(:unpublished)

end

dating/app/controllers/web/admin/dating_events_controller.rb
class Web::Admin::DatingEventsController < Web::Admin::ApplicationController
  def index
    params[:search] ||= {:meta_sort => "id.desc"}
    @search = DatingEvent.metasearch(params[:search])
    @dating_events = @search.page params[:page]
    headline headline_translate(:title)
  end

  def new
    @dating_event = DatingEvent.new
    headline headline_translate(:title)
  end

  def create
    @dating_event = DatingEvent.new(params[:dating_event])
    if @dating_event.save
      flash[:success] = flash_translate(:success)
      redirect_to edit_admin_dating_event_path(@dating_event.id)
    else
      flash[:error] = flash_translate(:error)
      render :action => :new
    end
  end

  def edit
    @dating_event = DatingEvent.find(params[:id])
    headline headline_translate(:title)
  end

  def update
    @dating_event = DatingEvent.find(params[:id])
    if @dating_event.update_attributes(params[:dating_event])
      flash[:success] = flash_translate(:success)
      redirect_to admin_dating_events_path
    else
      flash[:error] = flash_translate(:error)
      redirect_to edit_admin_dating_event_path(@dating_event.id)
    end
  end

  def destroy
    @dating_event = DatingEvent.find(params[:id])
    if @dating_event.destroy
      flash[:success] = flash_translate(:success)
    else
      flash[:error] = flash_translate(:error)
    end
    redirect_to admin_dating_events_path
  end

  def show
    redirect_to edit_admin_dating_event_path(params[:id])
  end
end

dating/app/helpers/web/admin/dating_events_helper.rb
module Web::Admin::DatingEventsHelper
end

dating/app/views/web/admin/dating_events/_form.html.haml
- if f.error_notification
  .alert.error.fade.in= f.error_notification
%ul.nav.nav-tabs
  %li.active
    %a{:"data-toggle" => "tab", :href => "#infoTab"}= t(".tab.info_tab")
  %li
    %a{:"data-toggle" => "tab", :href => "#settingsTab"}= t(".tab.settings_tab")
.tab-content
  #infoTab.tab-pane.active
    = f.input :name, :input_html => { :class => "span6" }
    = f.input :birthdate, :as => :string, :input_html => { :class => "datepicker" }
    = f.input :sex, :as => :select, :collection => ActionRequest.avaliable_sexs, :include_blank => false
    = f.input :phone, :input_html => { :class => "span6" }
    = f.input :email, :input_html => { :class => "span6" }
    = f.association :dating_event
    = f.input :cost, :input_html => { :class => "span6" }
    = f.input :coupone_code, :input_html => { :class => "span6" }
  #settingsTab.tab-pane
= f.button :submit

dating/app/views/web/admin/dating_events/edit.html.haml
= simple_form_for @action_request, :url => admin_action_request_path(@action_request), :html => {:class => "form-horizontal"} do |f|
  = render "form", :f => f

dating/app/views/web/admin/dating_events/index.html.haml
- if @action_requests.any?
  %table.table.table-striped.table-bordered.table-condensed
    %thead
      %tr
        %td= sort_link @search, :id, ActionRequest.human_attribute_name(:id)
        %td= sort_link @search, :email, ActionRequest.human_attribute_name(:email)
        %td= sort_link @search, :name, ActionRequest.human_attribute_name(:name)
        %td= sort_link @search, :sex, ActionRequest.human_attribute_name(:sex)
        %td= sort_link @search, :created_at, ActionRequest.human_attribute_name(:created_at)
        %td= sort_link @search, :updated_at, ActionRequest.human_attribute_name(:updated_at)
        %td= t(".control")
    %tbody
      - @action_requests.each do |action_request|
        %tr
          %td= action_request.id
          %td= link_to action_request.email, edit_admin_action_request_path(action_request)
          %td= action_request.name
          %td= action_request.human_sex_name
          %td= l(action_request.created_at, :format => :full)
          %td= l(action_request.updated_at, :format => :full)
          %td
            = link_to edit_admin_action_request_path(action_request) do
              %i.icon-edit
            = link_to admin_action_request_path(action_request), :method => :delete, :data => { :confirm => t(".are_you_sure") } do
              %i.icon-trash

dating/app/views/web/admin/dating_events/new.html.haml
= simple_form_for @action_request, :url => admin_action_requests_path, :html => {:class => "form-horizontal"} do |f|
  = render "form", :f => f